[versions]
# libraries
annotations = "24.0.1"
mockito = "5.2.0"
httpcomponents = "5.2.1"

# plugins
dokka = "1.8.10"
kotlin = "1.8.10"
changelog = "2.0.0"
gradleIntelliJPlugin = "1.14.0"
qodana = "0.1.13"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
httpcomponents = { group = "org.apache.httpcomponents.client5", name = "httpclient5", version.ref = "httpcomponents" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
